# Default initial positions for Arm_URDF_2026's ros2_control fake system

initial_positions:
  dummy_ee_joint: 0
  ee_pitch: 0
  ee_roll: 0
  elbow: 0
  elbow_roll: 0
  shoulder: 0
  shoulder_joint: 0