# Default initial positions for Arm_URDF_2026's ros2_control fake system

initial_positions:
  elbow_joint: 0
  end_effector_pitch: 0
  gripper_roll: 0
  shoulder_joint: 0
  shoulder_link: 0
  wrist_link: 0