# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rover_arm_controller
    - end_effector_controller

  rover_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    action_ns: follow_joint_trajectory
    default: true
  end_effector_controller:
    type: GripperCommand
    joints:
      - joint_6
      - finger_joint_1
      - finger_joint_2
    action_ns: gripper_cmd
    default: true