# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_joint_controller
    - arm_ee_controller

  arm_joint_controller:
    type: FollowJointTrajectory
    joints:
      - virtual_joint
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: follow_joint_trajectory
    default: true
  arm_ee_controller:
    type: GripperCommand
    joints:
      - finger_joint_1
      - finger_joint_2
    action_ns: gripper_cmd
    default: true