# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rover_arm_controller
    - end_effector_controller

  rover_arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder
      - shoulder_joint
      - elbow
      - elbow_roll
      - ee_pitch
      - ee_roll
  end_effector_controller:
    type: GripperCommand
    joints:
      - dummy_ee_joint
    action_ns: gripper_cmd
    default: true