# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rover_arm_controller
    - end_effector_controller

  rover_arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_joint
      - shoulder_link
      - elbow_joint
      - wrist_link
      - end_effector_pitch
      - gripper_roll
    action_ns: follow_joint_trajectory
    default: true
  end_effector_controller:
    type: GripperCommand
    joints:
      - gripper_roll
    action_ns: gripper_cmd
    default: true