# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rover_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    end_effector_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rover_arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - shoulder_link
      - elbow_joint
      - wrist_link
      - end_effector_pitch
      - gripper_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
end_effector_controller:
  ros__parameters:
    joint: dummy_ee_joint