# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_ee_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_joint_controller:
  ros__parameters:
    joints:
      - virtual_joint
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_ee_controller:
  ros__parameters:
    joint: finger_joint_1