# Used to create an image for the CI so we don't wait 10 minutes for an env setup
FROM ros:humble-ros-base

# Prevent interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Install common system dependencies and snapd prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-colcon-common-extensions \
    python3-evdev \
    python3.10-venv \
    python3-colcon-package-selection \
    python3-rosdep \
    python3-vcstool \
    git \
    snapd \
    curl \
    # Add any extra APT packages here:
    ros-humble-ros2-controllers \
    ros-humble-moveit \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements-ci.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm /tmp/requirements.txt

RUN pip install --force-reinstall colcon-core setuptools==$(pip list --no-index --format=json |  jq -r '.[] | select(.name=="setuptools").version') 

RUN echo 'Y' | pip uninstall empy==4.2  
RUN echo 'Y' | pip install empy==3.3.4 

# Automatically source ROS 2 setup in all subshells
RUN echo "source /opt/ros/humble/setup.bash" >> /etc/bash.bashrc
ENV BASH_ENV=/etc/bash.bashrc

WORKDIR /arm_ros2_ws