name: ROS2 Humble CI

on:
  push:
    branches: [ main, git_ci_setup ]
  pull_request:
    branches: [ main ]

jobs:
  ros2-build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          path: 'src/rsx_arm'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Setup ROS 2 Environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      # Install deps from package.xml files
      - name: Install System Dependencies (rosdep)
        working-directory: src/rsx_arm
        run: |
          source /opt/ros/humble/setup.bash
          sudo rosdep init || true # Don't crash if already initialized
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      # Build packages and properly set up the env
      # For some reason the CI environment has a hard time finding 
      # the globally installed colcon extensions in the script
      - name: Environment setup + tests
        working-directory: src/rsx_arm
        run: |
          python3 -m pip install --upgrade --force-reinstall colcon-common-extensions colcon-package-selection
          source humble-setup.sh
          echo -e "\e[32mEnvironment successfully built. Running unit tests...\e[0m"
          colcon test --ctest-args tests --packages-skip arm_msgs --return-code-on-test-failure